### ISSUE TITLE
Any plans to add make this async-compatible?

### ISSUE THREAD

**Issue by staktrace** [viniciusgerevini/sse-client#10]
Do you have any plans to make this more compatible with async setups? In particular I'd like to be able to get a `tokio::sync::mpsc::UnboundedReceiver` instead of a `std::sync::mpsc::Receiver` so that I can use `tokio::select!` on the result.

**Comment by staktrace** [comment]
Actually, never mind. I just found the `sse_codec` crate which seems async-friendly already.

**Comment by viniciusgerevini** [comment]
Thanks. I'm happy you found another one. I did think about adding async support in the past, but I couldn't find a scenario where it would be useful. You gave me a good one. I'll probably look a little bit more into this. Cheers.
