### ISSUE TITLE
`event_stream_handshake` strips query from URL without warning

### ISSUE THREAD

**Issue by Cldfire** [viniciusgerevini/sse-client#11]
I was trying to use this crate to write tests for a project of mine using https://github.com/klemens/hyper-sse. `hyper-sse` sets things up so that you register with the server using a token provided via a query parameter, like so (lifted from [this example](https://github.com/klemens/hyper-sse/blob/master/examples/terminal.rs)):

```rust
PUSH_SERVER.spawn(addr);
let auth_token = PUSH_SERVER.generate_auth_token(Some(0)).unwrap();

println!("Use the following command to connect to the SSE push server:");
println!("  curl http://[::1]:3000/push/0?{}", auth_token);
```

Unfortunately I was unable to get `sse-client` to successfully connect to the `hyper-sse` server; I just kept getting `400` response codes as my first event.

After some time spent debugging, I eventually tracked down why:

https://github.com/viniciusgerevini/sse-client/blob/6d501ca0a80b1bcce1861791ff8826066854b1dd/src/network.rs#L205-L210

Query parameters are stripped from the URL at the top of the function and never added back after that.

**Comment by viniciusgerevini** [comment]
Hi @Cldfire, thanks a lot for finding this error. I'm sorry you had to spend time tracking it.
I'll send a fix soon. ;)

**Comment by Cldfire** [comment]
Thanks for the quick reply, I appreciate it!
