### ISSUE TITLE
Dual license as MIT/Apache-2

### ISSUE THREAD

**Issue by jhpratt** [viniciusgerevini/sse-client#6]
See [rust-lang API docs](https://rust-lang-nursery.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) for a brief explanation as to why this is a good idea.

**Comment by viniciusgerevini** [comment]
Hello @jhpratt. Sorry, I totally missed this one.
Thanks for the information, I've read a little bit more about that and I'll be adding the dual license soon. Cheers.
